version: '3.1'
services:
  web:
    container_name: student
    image: student
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
  postgresql:
    container_name: sample_postgres
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=Praful@565
      - POSTGRES_USER=postgres
      - POSTGRES_DB=student
    ports:
      - "8181:8181"