apiVersion: v1
kind: Service
metadata:
  labels:
    app: student-project
  name: student-project
spec:
  ports:
    - name: student-project
      port: 8080
      protocol: TCP
  selector:
    app: student-project
  type: LoadBalancer
